import { Project } from '../types/project';

export const projectsAR: Project[] = [
  {
    id: '1',
    title: 'مقر تشانكايا السكني',
    description: 'مشروع سكني من 5 طوابق بخطوط معمارية حديثة. تصميم غني بشرفات واسعة وتفاصيل حجرية طبيعية.',
    image_url: '/projects/building_1.png',
    location: 'أنقرة، تركيا',
    year: 2024,
    category: 'سكني',
    display_order: 1,
    status: 'completed',
  },
  {
    id: '2',
    title: 'كارشياكا لوفت ريزيدنس',
    description: 'مشروع سكني بوتيكي من 4 طوابق مبني بنهج تصميم معاصر. شرفات زجاجية حديثة وأنظمة موفرة للطاقة.',
    image_url: '/projects/building_2.png',
    location: 'إزمير، تركيا',
    year: 2024,
    category: 'سكني',
    display_order: 2,
    status: 'in-progress',
  },
  {
    id: '3',
    title: 'نيلوفر الكلاسيكية السكنية',
    description: 'مجمع سكني مرموق من 5 طوابق مصمم بأسلوب نيوكلاسيكي. يتميز بخطوط أنيقة وشرفات واسعة.',
    image_url: '/projects/building_3.png',
    location: 'بورصة، تركيا',
    year: 2023,
    category: 'سكني',
    display_order: 3,
    status: 'completed',
  },
  {
    id: '4',
    title: 'مقر أوزتشليك للإنشاءات',
    description: 'مبنى مكاتب من الجيل الجديد مع بناء فولاذي حديث. واجهات زجاجية كبيرة ومناطق وظيفية متعددة الأغراض.',
    image_url: '/projects/building_4.png',
    location: 'إسطنبول، تركيا',
    year: 2024,
    category: 'تجاري',
    display_order: 4,
    status: 'in-progress',
  },
  {
    id: '5',
    title: 'أوكتشليك ريزيدنس',
    description: 'مشروع سكني حديث من 4 طوابق يقع في وسط المدينة. مساحات معيشية موجهة نحو الراحة مع هيكل فولاذي.',
    image_url: '/projects/building_5.png',
    location: 'أنقرة، تركيا',
    year: 2024,
    category: 'استخدام مختلط',
    display_order: 5,
    status: 'in-progress',
  },
];