import { Project } from '../types/project';

export const projectsAR: Project[] = [
  {
    id: '1',
    title: 'مركز إسطنبول المالي',
    description: 'مركز مالي من 52 طابقًا تم بناؤه بالبناء الفولاذي الحديث. مساحة بناء إجمالية 180,000 متر مربع. هيكل فولاذي مقاوم للزلازل ونظام واجهة زجاجية حديثة.',
    image_url: 'https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg',
    location: 'إسطنبول، تركيا',
    year: 2023,
    category: 'تجاري',
    display_order: 1,
    status: 'completed',
  },
  {
    id: '2',
    title: 'جسر عبور الخليج',
    description: 'جسر معلق بكابلات فولاذية بطول 3.2 كم. سعة يومية 45,000 مركبة. تم بناؤه وفقًا لمعايير الهندسة الأوروبية.',
    image_url: 'https://images.pexels.com/photos/681368/pexels-photo-681368.jpeg',
    location: 'إزمير، تركيا',
    year: 2022,
    category: 'بنية تحتية',
    display_order: 2,
    status: 'completed',
  },
  {
    id: '3',
    title: 'منشأة الإنتاج الصناعي',
    description: 'مساحة مغلقة 85,000 متر مربع. هيكل فولاذي مصمم خصيصًا للصناعة الثقيلة. تم دمج البنية التحتية الآلية الكاملة.',
    image_url: 'https://images.pexels.com/photos/1095814/pexels-photo-1095814.jpeg',
    location: 'جبزة، تركيا',
    year: 2023,
    category: 'صناعي',
    display_order: 3,
    status: 'completed',
  },
  {
    id: '4',
    title: 'مجمع أنقرة السكني',
    description: 'مجمع سكني حديث يحتوي على 250 وحدة. بناء فولاذي وخرسانة مسلحة، 8 طوابق. يتميز بمساحات خضراء وخدمات تجارية في الطابق الأرضي.',
    image_url: '/public/projects/chatgpt_image_17_ara_2025_23_04_34.png',
    location: 'أنقرة، تركيا',
    year: 2023,
    category: 'سكني',
    display_order: 4,
    status: 'completed',
  },
  {
    id: '5',
    title: 'برج إزمير السكني',
    description: 'برج سكني فاخر يحتوي على 180 شقة. 15 طابقًا بإطلالة على البحر. بناء هيكل فولاذي حديث مع أنظمة عالية الكفاءة في استهلاك الطاقة.',
    image_url: '/public/projects/chatgpt_image_17_ara_2025_22_37_41.png',
    location: 'إزمير، تركيا',
    year: 2023,
    category: 'سكني',
    display_order: 5,
    status: 'completed',
  },
  {
    id: '6',
    title: 'منطقة بورصة للأعمال',
    description: 'منطقة استخدام متعدد الأغراض للتجارة والسكن. تطوير استخدام مختلط يتضمن مساحات مكاتب وتجزئة وسكنية. هيكل فولاذي وواجهة حديثة.',
    image_url: '/public/projects/gemini_generated_image_g3n0pag3n0pag3n0.png',
    location: 'بورصة، تركيا',
    year: 2024,
    category: 'استخدام مختلط',
    display_order: 6,
    status: 'completed',
  },
  {
    id: '7',
    title: 'مشروع تطوير أنقرة السكني',
    description: 'تطوير سكني معاصر بتصميم معماري منتج. ميزات هندسية إنشائية متقدمة. المرحلة الأولى قيد الإنشاء حاليًا. تاريخ الانتهاء المتوقع 2025.',
    image_url: '/public/projects/chatgpt_image_17_ara_2025_22_59_36.png',
    location: 'أنقرة، تركيا',
    year: 2024,
    category: 'سكني',
    display_order: 7,
    status: 'in-progress',
  },
];
