import { Project } from '../types/project';

export const projectsEN: Project[] = [
  {
    id: '1',
    title: 'Çankaya Residence',
    description: '5-story residential project with modern architectural lines. Design enriched with spacious balconies and natural stone details.',
    image_url: '/projects/building_1.png',
    location: 'Ankara, Turkey',
    year: 2024,
    category: 'Residential',
    display_order: 1,
    status: 'completed',
  },
  {
    id: '2',
    title: 'Karşıyaka Loft Residence',
    description: '4-story boutique residential project built with contemporary design approach. Modern glass balconies and energy-efficient systems.',
    image_url: '/projects/building_2.png',
    location: 'Izmir, Turkey',
    year: 2024,
    category: 'Residential',
    display_order: 2,
    status: 'in-progress',
  },
  {
    id: '3',
    title: 'Nilüfer Classic Residences',
    description: '5-story prestigious residential complex designed in neo-classical style. Stands out with elegant lines and spacious balconies.',
    image_url: '/projects/building_3.png',
    location: 'Bursa, Turkey',
    year: 2023,
    category: 'Residential',
    display_order: 3,
    status: 'completed',
  },
  {
    id: '4',
    title: 'Özçelik Construction Headquarters',
    description: 'New generation office building with modern steel construction. Large glass facades and multi-purpose functional areas.',
    image_url: '/projects/building_4.png',
    location: 'Istanbul, Turkey',
    year: 2024,
    category: 'Commercial',
    display_order: 4,
    status: 'in-progress',
  },
  {
    id: '5',
    title: 'Ozcelik Residence',
    description: '4-story modern residential project located in city center. Comfort-oriented living spaces with steel frame construction.',
    image_url: '/projects/building_5.png',
    location: 'Ankara, Turkey',
    year: 2024,
    category: 'Mixed-Use',
    display_order: 5,
    status: 'in-progress',
  },
];