import { Project } from '../types/project';

export const projectsEN: Project[] = [
  {
    id: '1',
    title: 'Istanbul Financial Center',
    description: 'A 52-story financial center built with modern steel construction. Total construction area of 180,000 m². Features earthquake-resistant steel frame and modern glass facade system.',
    image_url: 'https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg',
    location: 'Istanbul, Turkey',
    year: 2023,
    category: 'Commercial',
    display_order: 1,
    status: 'completed',
  },
  {
    id: '2',
    title: 'Gulf Crossing Bridge',
    description: 'A 3.2 km long steel cable-stayed bridge. Daily capacity of 45,000 vehicles. Built with advanced European engineering standards.',
    image_url: 'https://images.pexels.com/photos/681368/pexels-photo-681368.jpeg',
    location: 'İzmir, Turkey',
    year: 2022,
    category: 'Infrastructure',
    display_order: 2,
    status: 'completed',
  },
  {
    id: '3',
    title: 'Industrial Production Facility',
    description: '85,000 m² enclosed area. Steel structure specially designed for heavy industry. Complete automation infrastructure integrated.',
    image_url: 'https://images.pexels.com/photos/1095814/pexels-photo-1095814.jpeg',
    location: 'Gebze, Turkey',
    year: 2023,
    category: 'Industrial',
    display_order: 3,
    status: 'completed',
  },
  {
    id: '4',
    title: 'Ankara Residential Complex',
    description: 'Modern residential complex with 250 units. Steel and reinforced concrete construction with 8 floors. Features green spaces and commercial areas on ground level.',
    image_url: '/public/projects/chatgpt_image_17_ara_2025_23_04_34.png',
    location: 'Ankara, Turkey',
    year: 2023,
    category: 'Residential',
    display_order: 4,
    status: 'completed',
  },
  {
    id: '5',
    title: 'Izmir Residential Tower',
    description: 'Luxury residential tower with 180 apartments. 15 floors with sea view. Modern steel frame construction with energy-efficient systems.',
    image_url: '/public/projects/chatgpt_image_17_ara_2025_22_37_41.png',
    location: 'Izmir, Turkey',
    year: 2023,
    category: 'Residential',
    display_order: 5,
    status: 'completed',
  },
  {
    id: '6',
    title: 'Bursa Business District',
    description: 'Multi-functional commercial and residential district. Mixed-use development with office spaces, retail, and residential units. Steel frame with modern facade.',
    image_url: '/public/projects/gemini_generated_image_g3n0pag3n0pag3n0.png',
    location: 'Bursa, Turkey',
    year: 2024,
    category: 'Mixed-Use',
    display_order: 6,
    status: 'completed',
  },
  {
    id: '7',
    title: 'Ankara Residential Development',
    description: 'Contemporary residential development featuring architectural design with advanced structural engineering. Phase 1 currently under construction. Estimated completion 2025.',
    image_url: '/public/projects/chatgpt_image_17_ara_2025_22_59_36.png',
    location: 'Ankara, Turkey',
    year: 2024,
    category: 'Residential',
    display_order: 7,
    status: 'in-progress',
  },
];
