import { Project } from '../types/project';

export const projectsTR: Project[] = [
  {
    id: '1',
    title: 'Çankaya Rezidans',
    description: 'Modern mimari çizgilere sahip 5 katlı konut projesi. Geniş balkonlar ve doğal taş detaylarla zenginleştirilmiş tasarım.',
    image_url: '/projects/building_1.png',
    location: 'Ankara, Türkiye',
    year: 2024,
    category: 'Konut',
    display_order: 1,
    status: 'completed',
  },
  {
    id: '2',
    title: 'Karşıyaka Loft Residence',
    description: 'Çağdaş tasarım anlayışıyla inşa edilen 4 katlı butik konut projesi. Modern cam balkonlar ve enerji verimli sistemler.',
    image_url: '/projects/building_2.png',
    location: 'İzmir, Türkiye',
    year: 2024,
    category: 'Konut',
    display_order: 2,
    status: 'in-progress',
  },
  {
    id: '3',
    title: 'Nilüfer Klasik Konutları',
    description: 'Neo-klasik mimari tarzda tasarlanmış 5 katlı prestijli konut kompleksi. Zarif çizgiler ve geniş balkonlarla dikkat çekiyor.',
    image_url: '/projects/building_3.png',
    location: 'Bursa, Türkiye',
    year: 2023,
    category: 'Konut',
    display_order: 3,
    status: 'completed',
  },
  {
    id: '4',
    title: 'Özçelik İnşaat Merkez Ofis',
    description: 'Modern çelik konstrüksiyon, geniş cam cepheler ve çok amaçlı kullanım alanlarına sahip yeni nesil ofis binası.',
    image_url: '/projects/building_4.png',
    location: 'İstanbul, Türkiye',
    year: 2024,
    category: 'Ticari',
    display_order: 4,
    status: 'in-progress',
  },
  {
    id: '5',
    title: 'Özçelik Residence',
    description: 'Şehir merkezinde 4 katlı modern konut projesi. Çelik çerçeve konstrüksiyon ile konfor odaklı yaşam alanları.',
    image_url: '/projects/building_5.png',
    location: 'Ankara, Türkiye',
    year: 2024,
    category: 'Karma Kullanım',
    display_order: 5,
    status: 'in-progress',
  },
];