import { Project } from '../types/project';

export const projectsEN: Project[] = [
  {
    id: '1',
    title: 'Çankaya Residence',
    description: '5-story residential project with modern architectural lines. Facade design enriched with spacious balconies and natural stone details. Total of 20 apartments, 4 independent units per floor.',
    image_url: '/projects/building_1.png',
    location: 'Ankara, Turkey',
    year: 2024,
    category: 'Residential',
    display_order: 1,
    status: 'completed',
  },
  {
    id: '2',
    title: 'Karşıyaka Loft Residence',
    description: '4-story boutique residential project built with contemporary design approach. Natural stone cladding ground floor, modern glass balconies and energy-efficient systems.',
    image_url: '/projects/building_2.png',
    location: 'Izmir, Turkey',
    year: 2024,
    category: 'Residential',
    display_order: 2,
    status: 'in-progress',
  },
  {
    id: '3',
    title: 'Nilüfer Classic Residences',
    description: '5-story prestigious residential complex designed in neo-classical architectural style. Column facade details, spacious balconies and elegant lines.',
    image_url: '/projects/building_3.png',
    location: 'Bursa, Turkey',
    year: 2023,
    category: 'Residential',
    display_order: 3,
    status: 'completed',
  },
  {
    id: '4',
    title: 'Özçelik Construction Headquarters',
    description: 'Company\'s new generation office and showroom building. Modern steel construction, large glass facades and multi-purpose areas. Showroom and office spaces on ground floor.',
    image_url: '/projects/building_4.png',
    location: 'Istanbul, Turkey',
    year: 2024,
    category: 'Commercial',
    display_order: 4,
    status: 'in-progress',
  },
  {
    id: '5',
    title: 'Okçelik Residence',
    description: '4-story modern residential project located in city center. Commercial areas on ground floor, comfort-oriented residential units on upper floors. Steel frame construction.',
    image_url: '/projects/building_5.png',
    location: 'Ankara, Turkey',
    year: 2024,
    category: 'Mixed-Use',
    display_order: 5,
    status: 'in-progress',
  },
];
