import { Project } from '../types/project';

export const projectsTR: Project[] = [
  {
    id: '1',
    title: 'Çankaya Rezidans',
    description: 'Modern mimari çizgilere sahip 5 katlı konut projesi. Geniş balkonlar ve doğal taş detaylarla zenginleştirilmiş cephe tasarımı. Toplam 20 daire, her katta 4 bağımsız bölüm.',
    image_url: '/projects/building_1.png',
    location: 'Ankara, Türkiye',
    year: 2024,
    category: 'Konut',
    display_order: 1,
    status: 'completed',
  },
  {
    id: '2',
    title: 'Karşıyaka Loft Residence',
    description: 'Çağdaş tasarım anlayışıyla inşa edilen 4 katlı butik konut projesi. Doğal taş kaplama zemin kat, modern cam balkonlar ve enerji verimli sistemler.',
    image_url: '/projects/building_2.png',
    location: 'İzmir, Türkiye',
    year: 2024,
    category: 'Konut',
    display_order: 2,
    status: 'in-progress',
  },
  {
    id: '3',
    title: 'Nilüfer Klasik Konutları',
    description: 'Neo-klasik mimari tarzda tasarlanmış 5 katlı prestijli konut kompleksi. Sütunlu cephe detayları, geniş balkonlar ve zarif çizgiler.',
    image_url: '/projects/building_3.png',
    location: 'Bursa, Türkiye',
    year: 2023,
    category: 'Konut',
    display_order: 3,
    status: 'completed',
  },
  {
    id: '4',
    title: 'Özçelik İnşaat Merkez Ofis',
    description: 'Firmanın yeni nesil ofis ve showroom binası. Modern çelik konstrüksiyon, geniş cam cepheler ve çok amaçlı kullanım alanları. Zemin katta showroom ve ofis alanları.',
    image_url: '/projects/building_4.png',
    location: 'İstanbul, Türkiye',
    year: 2024,
    category: 'Ticari',
    display_order: 4,
    status: 'in-progress',
  },
  {
    id: '5',
    title: 'Okçelik Residence',
    description: 'Şehir merkezinde konumlanmış 4 katlı modern konut projesi. Zemin katta ticari alanlar, üst katlarda konfor odaklı konut birimleri. Çelik çerçeve konstrüksiyon.',
    image_url: '/projects/building_5.png',
    location: 'Ankara, Türkiye',
    year: 2024,
    category: 'Karma Kullanım',
    display_order: 5,
    status: 'in-progress',
  },
];
