import { Project } from '../types/project';

export const projectsTR: Project[] = [
  {
    id: '1',
    title: 'İstanbul Finans Merkezi',
    description: 'Modern çelik konstrüksiyon ile inşa edilen 52 katlı finans merkezi. Toplam 180.000 m² inşaat alanı. Depreme dayanıklı çelik çerçeve ve modern cam cephe sistemi.',
    image_url: 'https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg',
    location: 'İstanbul, Türkiye',
    year: 2023,
    category: 'Ticari',
    display_order: 1,
    status: 'completed',
  },
  {
    id: '2',
    title: 'Körfez Geçiş Köprüsü',
    description: '3.2 km uzunluğunda çelik kablo askılı köprü. Günlük 45.000 araç kapasiteli. Avrupa mühendislik standartları ile inşa edilmiştir.',
    image_url: 'https://images.pexels.com/photos/681368/pexels-photo-681368.jpeg',
    location: 'İzmir, Türkiye',
    year: 2022,
    category: 'Altyapı',
    display_order: 2,
    status: 'completed',
  },
  {
    id: '3',
    title: 'Endüstriyel Üretim Tesisi',
    description: '85.000 m² kapalı alan. Ağır sanayi için özel tasarlanmış çelik strüktür. Tam otomasyon altyapısı entegre edilmiştir.',
    image_url: 'https://images.pexels.com/photos/1095814/pexels-photo-1095814.jpeg',
    location: 'Gebze, Türkiye',
    year: 2023,
    category: 'Endüstriyel',
    display_order: 3,
    status: 'completed',
  },
  {
    id: '4',
    title: 'Ankara Konut Kompleksi',
    description: '250 birimli modern konut kompleksi. Çelik ve betonarme konstrüksiyon, 8 kat. Zemin katta yeşil alanlar ve ticari alanlar mevcuttur.',
    image_url: '/public/projects/chatgpt_image_17_ara_2025_23_04_34.png',
    location: 'Ankara, Türkiye',
    year: 2023,
    category: 'Konut',
    display_order: 4,
    status: 'completed',
  },
  {
    id: '5',
    title: 'İzmir Konut Kulesi',
    description: '180 daireli lüks konut kulesi. 15 kat, deniz manzaralı. Modern çelik çerçeve konstrüksiyon, enerji verimliliği yüksek sistemler.',
    image_url: '/public/projects/chatgpt_image_17_ara_2025_22_37_41.png',
    location: 'İzmir, Türkiye',
    year: 2023,
    category: 'Konut',
    display_order: 5,
    status: 'completed',
  },
  {
    id: '6',
    title: 'Bursa İş Merkezi',
    description: 'Çok amaçlı ticari ve konut alanı. Ofis, perakende ve konut birimlerini içeren karma kullanım gelişimi. Çelik çerçeve ve modern cephe.',
    image_url: '/public/projects/gemini_generated_image_g3n0pag3n0pag3n0.png',
    location: 'Bursa, Türkiye',
    year: 2024,
    category: 'Karma Kullanım',
    display_order: 6,
    status: 'completed',
  },
  {
    id: '7',
    title: 'Ankara Konut Gelişim Projesi',
    description: 'Ürün mimarisi ile çağdaş konut gelişimi. Gelişmiş yapısal mühendislik özellikleri. 1. Faz şu anda inşaat halinde. Tahmini tamamlanma tarihi 2025.',
    image_url: '/public/projects/chatgpt_image_17_ara_2025_22_59_36.png',
    location: 'Ankara, Türkiye',
    year: 2024,
    category: 'Konut',
    display_order: 7,
    status: 'in-progress',
  },
];
