import { Project } from '../types/project';

export const projectsAR: Project[] = [
  {
    id: '1',
    title: 'مقر تشانكايا السكني',
    description: 'مشروع سكني من 5 طوابق بخطوط معمارية حديثة. تصميم واجهة غني بشرفات واسعة وتفاصيل حجرية طبيعية. إجمالي 20 شقة، 4 وحدات مستقلة في كل طابق.',
    image_url: '/projects/building_1.png',
    location: 'أنقرة، تركيا',
    year: 2024,
    category: 'سكني',
    display_order: 1,
    status: 'completed',
  },
  {
    id: '2',
    title: 'كارشياكا لوفت ريزيدنس',
    description: 'مشروع سكني بوتيكي من 4 طوابق مبني بنهج تصميم معاصر. كسوة حجرية طبيعية في الطابق الأرضي، شرفات زجاجية حديثة وأنظمة موفرة للطاقة.',
    image_url: '/projects/building_2.png',
    location: 'إزمير، تركيا',
    year: 2024,
    category: 'سكني',
    display_order: 2,
    status: 'in-progress',
  },
  {
    id: '3',
    title: 'نيلوفر الكلاسيكية السكنية',
    description: 'مجمع سكني مرموق من 5 طوابق مصمم بأسلوب معماري نيوكلاسيكي. تفاصيل واجهة بأعمدة، شرفات واسعة وخطوط أنيقة.',
    image_url: '/projects/building_3.png',
    location: 'بورصة، تركيا',
    year: 2023,
    category: 'سكني',
    display_order: 3,
    status: 'completed',
  },
  {
    id: '4',
    title: 'مقر أوزتشليك للإنشاءات',
    description: 'مبنى المكاتب وصالة العرض من الجيل الجديد للشركة. بناء فولاذي حديث، واجهات زجاجية كبيرة ومناطق متعددة الأغراض. صالة عرض ومساحات مكتبية في الطابق الأرضي.',
    image_url: '/projects/building_4.png',
    location: 'إسطنبول، تركيا',
    year: 2024,
    category: 'تجاري',
    display_order: 4,
    status: 'in-progress',
  },
  {
    id: '5',
    title: 'أوكتشليك ريزيدنس',
    description: 'مشروع سكني حديث من 4 طوابق يقع في وسط المدينة. مناطق تجارية في الطابق الأرضي، وحدات سكنية موجهة نحو الراحة في الطوابق العليا. بناء هيكل فولاذي.',
    image_url: '/projects/building_5.png',
    location: 'أنقرة، تركيا',
    year: 2024,
    category: 'استخدام مختلط',
    display_order: 5,
    status: 'in-progress',
  },
];
